// Mock Users Data
export const MOCK_USERS = [
  {
    id: '1',
    name: 'Dr. James Mitchell',
    email: 'j.mitchell@cpms.edu',
    password: 'password123',
    role: 'Admin',
    status: 'Active',
    phone: '+1-555-0100',
    address: '123 Administrative Way',
    city: 'New York',
    state: 'NY',
    country: 'USA',
    postal_code: '10001',
    bio: 'System Administrator',
    avatar_url: 'https://via.placeholder.com/150?text=Admin',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2025-03-01T00:00:00Z'
  },
  {
    id: '2',
    name: 'Ms. Sarah Thompson',
    email: 's.thompson@cpms.edu',
    password: 'password123',
    role: 'Custodian',
    status: 'Active',
    phone: '+1-555-0101',
    address: '456 Academic Avenue',
    city: 'Boston',
    state: 'MA',
    country: 'USA',
    postal_code: '02101',
    bio: 'Property Custodian, Information Technology Department',
    avatar_url: 'https://via.placeholder.com/150?text=Custodian',
    created_at: '2024-01-02T00:00:00Z',
    updated_at: '2025-03-02T00:00:00Z'
  },
  {
    id: '3',
    name: 'Dr. Robert Chen',
    email: 'r.chen@cpms.edu',
    password: 'password123',
    role: 'Auditor',
    status: 'Active',
    phone: '+1-555-0102',
    address: '789 Compliance Road',
    city: 'Los Angeles',
    state: 'CA',
    country: 'USA',
    postal_code: '90001',
    bio: 'Compliance and Audit Officer',
    avatar_url: 'https://via.placeholder.com/150?text=Auditor',
    created_at: '2024-01-03T00:00:00Z',
    updated_at: '2025-03-03T00:00:00Z'
  },
  {
    id: '4',
    name: 'Ms. Sarah Thompson',
    email: 'admin@gmail.com',
    password: 'admin',
    role: 'admin',
    status: 'Active',
    phone: '+1-555-0101',
    address: '456 Academic Avenue',
    city: 'Boston',
    state: 'MA',
    country: 'USA',
    postal_code: '02101',
    bio: 'Property Custodian, Information Technology Department',
    avatar_url: 'https://via.placeholder.com/150?text=Custodian',
    created_at: '2024-01-02T00:00:00Z',
    updated_at: '2025-03-02T00:00:00Z'
  },
]
